# This is a basic workflow to help you get started with Actions

name: deploy-container

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
    paths:
      - 'container/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
defaults:
  run:
    working-directory : container
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses : unfor19/install-aws-cli-action@v1
      - run : aws s3 sync dist s3://mfe-container-prod/container/latest
        env : 
          AWS_ACCESS_KEY_ID : AKIA3KAXCIFR6ER6DUTU
          AWS_SECRET_ACCESS_KEY : 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
